language: node_js
node_js:
  - "4"
  - "5"
  - "6"
script:
  - npm run check:src
  - npm run build
  - npm run check:examples
  - npm run test:cov-codacy
branches:
  only:
    - master
cache:
  directories:
  - $HOME/.npm
  - examples/async-fetch/node_modules
  - examples/async-fetch-vanilla/node_modules
  - examples/countdown/node_modules
  - examples/countdown-obs/node_modules
  - examples/form-validation/node_modules
  - examples/notification/node_modules
  - examples/single-file/node_modules
  - examples/single-file-redux/node_modules
